name: Create Zip File
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Generate ZIP
        uses: montudor/action-zip@v1
        with:
          args: zip -r dist/release.zip .
